### ISSUE TITLE
First line of the python script

### ISSUE THREAD

**Issue by Steamerzone** [pdxlocations/Meshtastic-MQTT-Connect#2]
Ensure that the shebang line at the top of your Python script is correctly pointing to the Python interpreter. Open the script in a text editor, and the first line should look something like this:

#!/usr/bin/env python3

This line tells the system how to interpret the script.

**Comment by pdxlocations** [comment]
Thanks, I'm not an experienced developer.  Any help is greatly appreciated!

**Comment by Steamerzone** [comment]
ChatGPT helped me with this info. :-)

**Comment by pdxlocations** [comment]
Funny, ChatGPT wrote most of the code and never mention this detail, lol.
Already someone is using the client and mentioned the fix on public MQTT.

**Comment by Steamerzone** [comment]
That's me on MQTT. :-)
