### ISSUE TITLE
Positions table not populating

### ISSUE THREAD

**Issue by f16flcn** [pdxlocations/Meshtastic-MQTT-Connect#43]
Hi Team,

Apologies in advance - I'm not proficient enough in Python to submit a pull request.

Have the latest version of the script running well, except the positions table is not populating.

![image](https://github.com/pdxlocations/Meshtastic-MQTT-Connect/assets/4203209/fd1f6c46-c46e-47cd-9c2c-2b184e0f096f)

Position messages are being received on the channel:

![image](https://github.com/pdxlocations/Meshtastic-MQTT-Connect/assets/4203209/1e925edb-4f97-44e5-92f4-d3776809130f)

Have updated the mcc_map.py file to look at the correct table:

![image](https://github.com/pdxlocations/Meshtastic-MQTT-Connect/assets/4203209/e2bf6145-7a7c-4cd4-b80e-a626a815af5f)

(might be helpful to have a comment to update this if a non standard channel / mqtt broker is used.

Thank you!

**Comment by pdxlocations** [comment]
It's not documented yet but you need to set record_locations = True on line 44 of the code.

**Comment by f16flcn** [comment]
Thank you! that resolved the issue. Locations are being recorded into DB. mmc-map.py is also correctly generating the html file. 

I presume that idea is to run mmc-may.py via a cron job to ensure updated mapping?

Again thank you for the great app.

**Comment by pdxlocations** [comment]
Great to hear!  The mapping feature isn't fully implemented.  I never thought of a nice way to do it so I've left it as it is.  My thoughts are that most positions don't change all that quickly, so it's easy to re-run the map script when an update is wanted.  Open to ideas though!

**Comment by f16flcn** [comment]
my solution that was quick and easy was node-red:
![image](https://github.com/pdxlocations/Meshtastic-MQTT-Connect/assets/4203209/9e097624-7314-46bf-b624-9c33ba509cc8)

also, used parts of your main script to make it none UI and more CLI based and then used it as a bases for integration for example with signal messenger:

![image](https://github.com/pdxlocations/Meshtastic-MQTT-Connect/assets/4203209/a245087e-c24e-40b6-a129-8851c378ed7c)

let me know please if you or anyone else is interested.

**Comment by pdxlocations** [comment]
> my solution that was quick and easy was node-red: ![image](https://private-user-images.githubusercontent.com/4203209/317702494-9e097624-7314-46bf-b624-9c33ba509cc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NTQ3MjMsIm5iZiI6MTcxMTY1NDQyMywicGF0aCI6Ii80MjAzMjA5LzMxNzcwMjQ5NC05ZTA5NzYyNC03MzE0LTQ2YmYtYjYyNC05YzMzYmE1MDljYzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMTkzMzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWQ0MThiOGZkODZkM2YzMDg4YmQ1MjMzZGY5YmIwODhhYTMzNWI5ODA1NDg0MTdjMjRmY2VmNDcyZGQ2YzdlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YzMpcc4iBRmy6OyxOBpukp1NxGwQnMKjYBwSiOlDPzY)
> 
> also, used parts of your main script to make it none UI and more CLI based and then used it as a bases for integration for example with signal messenger:
> 
> ![image](https://private-user-images.githubusercontent.com/4203209/317703172-a245087e-c24e-40b6-a129-8851c378ed7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NTQ3MjMsIm5iZiI6MTcxMTY1NDQyMywicGF0aCI6Ii80MjAzMjA5LzMxNzcwMzE3Mi1hMjQ1MDg3ZS1jMjRlLTQwYjYtYTEyOS04ODUxYzM3OGVkN2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMTkzMzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzRhYzA1ODJjMDQzNTQ3MjA4NWUzOWI1MDAwYjk0MjBmZDM0M2MwZDEwMDgxNjdkMDJjNTUyZGEwYTE3YzY3ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Pf4wnj2aNvF-USLSZiCIP6LK3ODRcifK2GQIYaRg9lA)
> 
> let me know please if you or anyone else is interested.

This is great!  I haven't gotten into RodeRED yet but it's amazing how much you can do with it!
