### ISSUE TITLE
mmc-map.py does not include the root topic when generating the database table name.

### ISSUE THREAD

**Issue by william-stearns** [pdxlocations/Meshtastic-MQTT-Connect#50]
The following two line change allows mmc-map.py to work again:

--- mmc-map.py.dist 2024-05-27 00:50:57.000000000 -0400
+++ mmc-map.py  2024-07-10 23:19:23.000000000 -0400
@@ -4,6 +4,7 @@
 from statistics import mean
 
 mqtt_broker = 'mqtt.meshtastic.org'
+topic = 'msh/US/2/e'
 channel = 'LongFast'
 
 def sanitize_string(input_str):
@@ -16,7 +17,7 @@
     sanitized_str = re.sub(r'[^a-zA-Z0-9_]', '_', input_str)
     return sanitized_str
 
-table = sanitize_string(mqtt_broker) + "_" + sanitize_string(channel) + "_positions"
+table = sanitize_string(mqtt_broker) + "_" + sanitize_string(topic) + "_" + sanitize_string(channel) + "_positions"
 
 # Connect to SQLite database
 conn = sqlite3.connect('mmc.db')

**Comment by william-stearns** [comment]
patch file attached
[mmc-map.add_topic.diff.txt](https://github.com/user-attachments/files/16171081/mmc-map.add_topic.diff.txt)

**Comment by pdxlocations** [comment]
Thank you!  fixed with your patch in https://github.com/pdxlocations/Meshtastic-MQTT-Connect/commit/7eb27d0e7546ba9f8a586b4cd0b71d4f83ed8c43
