### ISSUE TITLE
Move functions directly under imports, which pushes actual executable code down.

### ISSUE THREAD

**Issue by william-stearns** [pdxlocations/Meshtastic-MQTT-Connect#58]
pdxlocations, this is a proposed change.  Please give a thumbs up, thumbs down, or no preference, and any comments or requests.

**Comment by pdxlocations** [comment]
I do like having the debug options and default settings at the top of the script.  I think they may be overlooked if they were in the middle.  As for the rest, sure!

**Comment by william-stearns** [comment]
Completely agreed on the options/settings where the end-user can see them.  I'm also hoping to consider adding command line options so the user doesn't have to edit the script to change defaults, but haven't figured out how to do that yet without a lot of options.  Perhaps the user can specify a json preset file in which their preferred settings are stored?  (Thinking out loud)

**Comment by pdxlocations** [comment]
I've been working on a headless version of the script that does just this!
https://github.com/pdxlocations/Meshtastic-MQTTc

**Comment by pdxlocations** [comment]
closed by #61
